export class Movie {
  CanUserRate: string;
  Duration: string;
  EventCensor: string;
  EventCode: string;
  EventDimension: string;
  EventGenre: string;
  EventImageCode: string;
  EventIsDefault: string;
  EventLanguage: string;
  EventName: string;
  EventSearchTags: string;
  EventTitle: string;
  EventURL: string;
  IsAtmosEnabled: string;
  IsMovieClubEnabled: string;
  RegCode: string;
  ShowDate: string;
  TrailerURL: string;
  avgRating: number;
  criticCount: number;
  csCount: string;
  dwtsCount: number;
  maybeCount: number;
  totalVotes: number;
  trailerType: string;
  userCount: number;
  wtsCount: number;
}
